// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP baseCall(SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP posteriorFFC(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP ThinPlateRegistration(SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP _rcpp_module_boot_class_Stack();
RcppExport SEXP _rcpp_module_boot_methods_Display();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_class_Stack", (DL_FUNC) &_rcpp_module_boot_class_Stack, 0},
    {"_rcpp_module_boot_methods_Display", (DL_FUNC) &_rcpp_module_boot_methods_Display, 0},
    {"baseCall",              (DL_FUNC) &baseCall,              4},
    {"posteriorFFC",          (DL_FUNC) &posteriorFFC,          7},
    {"ThinPlateRegistration", (DL_FUNC) &ThinPlateRegistration, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_prickly(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
